### ISSUE TITLE
Site database backlog causing prereq check warning and upgrade to fail

### ISSUE THREAD

**Issue by TroyMartinNet** [MicrosoftDocs/SCCMdocs#1085] opened 2018-12-13 04:22 UTC
I'm having same issue as @PrajwalDesai. Followed the steps to cleanup the outstanding ChangeTracking tasks/jobs. Its not cleaning up the table syscommittab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db678f94-700f-ad35-9fdc-d165893b5373
* Version Independent ID: 2ee761db-4b3b-6fa0-c195-ad85ebbac70d
* Content: [Prerequisite checks - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/list-of-prerequisite-checks#bkmk_changetracking)
* Content Source: [sccm/core/servers/deploy/install/list-of-prerequisite-checks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/list-of-prerequisite-checks.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2018-12-14 17:54
Thanks for the feedback, and sorry for the problems. I'm closing this issue as a duplicate of #1076. You can subscribe to that issue to receive notifications.

**Closed by aczechowski** 2018-12-14 17:54 UTC
Labels: duplicate, triaged
