### ISSUE TITLE
Azure File storage support for Remote content library and package source

### ISSUE THREAD

**Issue by santoshseth** [MicrosoftDocs/SCCMdocs#1347] opened 2019-03-22 10:08 UTC
Is Azure File storage supported hosting the Remote content library and package source?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6a4e18-8d5c-dc3b-f189-cfeacd9f7b68
* Version Independent ID: 64456d54-bf60-ea66-4037-6995409375cb
* Content: [High availability - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/high-availability-options)
* Content Source: [sccm/core/servers/deploy/configure/high-availability-options.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/high-availability-options.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2019-03-25 21:21
Thanks @santoshseth for the feedback. It's a duplicate of #1285, here's my response:

We've not tested this configuration, so not sure if it will work, thus not supported. If Azure is sharing the content as any Windows file share, then it might just work. But again, not something we've tested. If you want the product to consider support for this scenario, please file [product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback). 

I'm closing this issue as there's nothing actionable for docs at this time; we don't generally document what we don't support.

**Closed by aczechowski** 2019-03-25 21:21 UTC
