### ISSUE TITLE
WVD is not i Preview

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/SCCMdocs#2262] opened 2020-03-16 16:11 UTC
"Windows Virtual Desktop is a preview feature of Microsoft Azure and Microsoft 365."

WVD went GA in September 2019: https://www.microsoft.com/en-us/microsoft-365/blog/2019/09/30/windows-virtual-desktop-generally-available-worldwide/

**Comment by aczechowski** [comment] 2020-03-20 22:13
Looks like a dupe of #2261

**Closed by aczechowski** 2020-03-20 22:13 UTC
Labels: duplicate
