### ISSUE TITLE
Could you please provide details instead

### ISSUE THREAD

**Issue by benoithamet** [MicrosoftDocs/SCCMdocs#1360] opened 2019-03-26 04:16 UTC
Hi there
this doco is definitively not helpful to enable TLS 1.2
This just refers to other doco which then refers also to other and there it is definitively not usefull
Please update this doco to provide exact configuration for enabling TLS 1.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db678f94-700f-ad35-9fdc-d165893b5373
* Version Independent ID: 2ee761db-4b3b-6fa0-c195-ad85ebbac70d
* Content: [Prerequisite checks - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/list-of-prerequisite-checks#feedback)
* Content Source: [sccm/core/servers/deploy/install/list-of-prerequisite-checks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/list-of-prerequisite-checks.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2019-03-26 19:07
Thanks @benoithamet for the feedback. This article is not intended to provide that information, and currently the linked KB article is the primary source for how to enable TLS. Revising that KB, and incorporating the content into the core docs is on my to do list. So I'm going to close this issue as a duplicate of #548. You can subscribe to that issue to receive notifications when anything changes.

**Closed by aczechowski** 2019-03-26 19:07 UTC
Labels: duplicate, triaged
