### ISSUE TITLE
Add URL for O365 Updates

### ISSUE THREAD

**Issue by StevenElTaino** [MicrosoftDocs/SCCMdocs#928] opened 2018-10-11 21:04 UTC
Please add http://officecdn.microsoft.com to approved URL list.  While not required specifically for the SCP, it is required on the top SUP/internet-facing if you are whitelisting URLs on a proxy server to download and deploy Office 365 updates.
See https://blogs.technet.microsoft.com/askpfeplat/2017/03/23/troubleshooting-office-365-proplus-patching-through-system-center-configuration-manager/ for reference.

P.S. I'm also looking for a section to add it to deploy O365 updates and setting up the SUP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26fc3067-8a85-2455-8b71-69cf46cbb7e0
* Version Independent ID: a90ca598-c5fa-f245-eafc-0fd95f9eaca9
* Content: [Service connection point - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/about-the-service-connection-point#bkmk_urls)
* Content Source: [sccm/core/servers/deploy/configure/about-the-service-connection-point.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/about-the-service-connection-point.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2018-10-18 16:01
I'm closing this issue as a duplicate of #929. If the URL isn't required for the SCP, then it's potentially confusing to include it here.

**Closed by aczechowski** 2018-10-18 16:01 UTC
Labels: duplicate, triaged
