### ISSUE TITLE
Add summary of changes link

### ISSUE THREAD

**Issue by BritV8** [MicrosoftDocs/SCCMdocs#1289] opened 2019-03-04 00:31 UTC
Would be good to add to the top 

Aside from new features, this release also includes additional changes such as bug fixes. For more information, see Summary of changes in System Center Configuration Manager current branch, version 1806.

https://support.microsoft.com/en-nz/help/4459701/summary-of-changes-in-system-center-configuration-manager-current-bran

like the 1802/1710 documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22765ffe-cef8-a88f-5f71-00caf9b47046
* Version Independent ID: cb5ad492-39d1-f63d-0bd2-7f3a0b1d8af0
* Content: [What's new in version 1806 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1806)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1806.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/whats-new-in-version-1806.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2019-03-04 21:26
Thanks @BritV8 for the feedback. That link *is* in this article, just moved to a new location. See the [other updates](https://docs.microsoft.com/sccm/core/plan-design/changes/whats-new-in-version-1806#other-updates) section. It includes a link to that article as well as other additional resources. I decided to move it to the bottom of the article to focus more on the new features, which is the point of the article. 

I'm going to close this issue, as this is currently by design. If you're passionate about it, please reopen and we can discuss (or post to the community for broader input).

**Closed by aczechowski** 2019-03-04 21:26 UTC
Labels: doc-provided, triaged
