### ISSUE TITLE
Link to PowerShell and SCCM docs broken

### ISSUE THREAD

**Issue by ramseygr** [MicrosoftDocs/SCCMdocs#879] opened 2018-10-02 22:43 UTC
from this page:
https://github.com/MicrosoftDocs/SCCMdocs

There's a link to here:
https://github.com/MicrosoftDocs/sccm-docs-powershell

but I receive a 404 when I try to go to that link. I tried to find the current location for sccm-docs-powershell (so I could fix the docs myself), but I can't find it!

**Comment by aczechowski** [comment] 2018-10-02 23:20
Thanks @ramseygr, that's a known issue, technically currently by design. The SCCM PowerShell repo is currently private. So that note there (good sleuthing!) is mostly for my reference right now. But I do have a request with our ops team to make the PowerShell repo public. I don't have a specific timeline yet, so best I can say is "coming soon." I'm going to close this issue as there's nothing else actionable right now.

**Closed by aczechowski** 2018-10-02 23:20 UTC
Labels: docs-experience, triaged

**Comment by aczechowski** [comment] 2018-10-02 23:27
As a private repo, it only works for Microsoft authenticated users. Again, hoping to make it public soon.
