### ISSUE TITLE
Add summary of changes link

### ISSUE THREAD

**Issue by BritV8** [MicrosoftDocs/SCCMdocs#1290] opened 2019-03-04 00:32 UTC
Would be good to add to the top 

Aside from new features, this release also includes additional changes such as bug fixes. For more information, see Summary of changes in System Center Configuration Manager current branch, version 1810.

https://support.microsoft.com/en-nz/help/4482169/summary-of-changes-in-system-center-configuration-manager-1810

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dd4b289-bd23-a3ef-f778-9d7030d6f499
* Version Independent ID: b0bcb635-b4b8-ee2f-14d7-ce9f65d52982
* Content: [What's new in version 1810 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1810)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1810.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/whats-new-in-version-1810.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2019-03-04 21:23
I'm closing this issue as a duplicate of #1289

**Closed by aczechowski** 2019-03-04 21:23 UTC
Labels: duplicate, triaged
