### ISSUE TITLE
SQL Enterprise

### ISSUE THREAD

**Issue by faulknerp** [MicrosoftDocs/SCCMdocs#1077] opened 2018-12-08 13:10 UTC
SQL Enterprise is required for AlwaysOn (https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database).

As this page says approved SQL use rights with SCCM include "SQL Server Always On" does that confirm that SQL Enterprise is covered by the license that comes with SCCM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3b9a7fa-9585-a2fb-590e-0b74e128035d
* Version Independent ID: 9aae8e97-de68-c274-b4c6-cd925568c75b
* Content: [Product and Licensing FAQ - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/product-and-licensing-faq#product-and-licensing-faq)
* Content Source: [sccm/core/understand/product-and-licensing-faq.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/product-and-licensing-faq.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2018-12-11 04:49
Thanks @faulknerp for the question. I'm going to close this as a duplicate of existing issue #464 which includes this topic. I don't have an answer to your question right now, but there is a renewed effort underway to try to further clarify these questions.

**Closed by aczechowski** 2018-12-11 04:49 UTC
Labels: duplicate, triaged
