### ISSUE TITLE
Is E-HTTP MP mandatory?

### ISSUE THREAD

**Issue by ashutosh-3004** [MicrosoftDocs/SCCMdocs#2336] opened 2020-05-20 08:09 UTC
can you please clarify if E-HTTP is mandatory for using token based auth on clients? can client system use token based auth with HTTPS MPs and CMG functioning in environment but without Client systems having PKI cert?

**Comment by aczechowski** [comment] 2020-05-20 16:41
Closing as dupe of MicrosoftDocs/memdocs#270

**Closed by aczechowski** 2020-05-20 16:41 UTC
Labels: duplicate
