### ISSUE TITLE
Configuration Manager URLs

### ISSUE THREAD

**Issue by Stroell** [MicrosoftDocs/SCCMdocs#1316] opened 2019-03-13 09:43 UTC
Please document the Configuration Manager URLs that need to be whitelisted in the Proxy.
Example: https://blogs.technet.microsoft.com/configmgrdogs/2016/10/13/configuration-manager-proxy-exceptions/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 926d0167-454c-f8c0-177d-0b1de31b8a77
* Version Independent ID: e1a16df1-da95-3783-c683-cd80fe43bf6d
* Content: [Proxy server support - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/network/proxy-server-support)
* Content Source: [sccm/core/plan-design/network/proxy-server-support.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/network/proxy-server-support.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2019-03-18 19:29
Thanks @Stroell for the feedback. I'm going to close this as a duplicate of #714. That issue notes a few articles that already have some URLs listed

**Closed by aczechowski** 2019-03-18 19:29 UTC
Labels: duplicate, triaged
