### ISSUE TITLE
Windows 10 version 1810

### ISSUE THREAD

**Issue by MikhailCompo** [MicrosoftDocs/SCCMdocs#1581] opened 2019-05-23 16:10 UTC
Does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e01e1f4e-9da8-331c-4a4b-74480571a37a
* Version Independent ID: 7933dc64-42dd-1e13-73d1-010bc02124fd
* Content: [Technical preview 1905 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/2019/technical-preview-1905?__s=h8g4nbc4aggxnjxgjw3s#feedback)
* Content Source: [sccm/core/get-started/2019/technical-preview-1905.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/2019/technical-preview-1905.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2019-05-23 17:17
Duplicate of #1576, change should publish later today.

**Closed by aczechowski** 2019-05-23 17:17 UTC
Labels: duplicate, triaged
