### ISSUE TITLE
Multiple CM instances in a single Tennant?  

### ISSUE THREAD

**Issue by mattwailes** [MicrosoftDocs/SCCMdocs#2319] opened 2020-04-14 19:43 UTC
If my org has multiple CM instances (hierarchy's) on separate forests that are sharing a single Azure tenant can my tenant support multiple CMG's from the different instances? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a99f1b09-f669-e3c8-e9a1-c2594f329e12
* Version Independent ID: b022b0cd-f045-418a-be0e-f15f699f9d35
* Content: [CMG FAQ - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/manage/cmg/cloud-management-gateway-faq)
* Content Source: [sccm/core/clients/manage/cmg/cloud-management-gateway-faq.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/cloud-management-gateway-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2020-04-22 00:07
I think this is a dupe of #2305, see my response there.

**Closed by aczechowski** 2020-04-22 00:07 UTC
Labels: duplicate
