### ISSUE TITLE
smsdbrole_MPUserSvc when using management point connection account

### ISSUE THREAD

**Issue by zygentoma** [MicrosoftDocs/SCCMdocs#2056] opened 2019-12-05 12:35 UTC
The documentation states: "smsdbrole_MPUserSvc: Management Point Application Request. ConfigMgr grants this permission to the computer account that host the Management Point to support user-based application requests." 
It does not mention that when using a management point connection account the connection account needs to be a member of smsdbrole_MPUserSvc otherwise available user deployments do not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f80cf3-6f36-cb44-d0e5-d186164d6281
* Version Independent ID: ada8a281-7d9f-e82e-e4e8-056b93e8b36d
* Content: [Accounts used - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/accounts#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/accounts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/accounts.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2019-12-05 19:45
Thanks @zygentoma for filing this. I checked with one of our engineers. You shouldn't have to do this manually, as hierarchy manager (hman) should manage these permissions. If that's *not* happening, then it could be a bug or something environmental. We haven't seen this issue in our testing, hman automatically adds/removes permissions.

I'm going to close this doc issue. Can you please [file a frown](https://docs.microsoft.com/en-us/configmgr/core/understand/find-help#product-feedback) so that our engineering team can investigate further?

**Closed by aczechowski** 2019-12-05 19:45 UTC
Labels: product-feedback, triaged

**Comment by zygentoma** [comment] 2019-12-06 11:00
I think this slightly missing the point as yes, I did have an issue after upgrading to 1906 and removing the application catalog points that led me having to add the account manually but this documentation isn't saying that you should manually grant this permission to the computer account that host the Management Point either, it's documenting the expected outcome after hman configures the permissions.

Bart

Bartholomew Hoskins
Workplace Engineering
AXA Group Operations
Nightingale House, Redland Hill, Redland, Bristol BS6 6SH UK
Tel: +44 (0)7977 918265 (int: 611 8265)

**Comment by aczechowski** [comment] 2019-12-06 16:24
@zygentoma my point is that we think the documentation is correct in terms of the intended behavior, but there may be some product defect. So need you to file a frown to send info to the engineering team to investigate. It's possible there's some environmental aspect as well, which would require a support case. But we suggest starting with sending product feedback. Thanks!
