### ISSUE TITLE
Not available for everyone?

### ISSUE THREAD

**Issue by Krytical13** [MicrosoftDocs/SCCMdocs#1397] opened 2019-04-04 01:01 UTC
This article does not talk about the fact that this update (1902) is not available for everyone yet...
Someone on Reddit says there is a way to enable "fast ring" updates or something to allow you to update to 1902..

But so far our SCCM is fully up to date (1810, 5.1810.1075.2600, 5.0.8740.1000)
Using the Online service connection point, and no proxy configured (checked IE settings too, no auto config)
Yet 1902 is not showing up after checking for updates nearly every day.
This leads me to believe it's related to Microsoft staggering the release somehow..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d3b085-a171-f4ff-bc1b-d2ef4d391839
* Version Independent ID: c0a9e2ce-5915-386b-ddc6-a3c549e41686
* Content: [Checklist for 1902 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/checklist-for-installing-update-1902)
* Content Source: [sccm/core/servers/manage/checklist-for-installing-update-1902.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/checklist-for-installing-update-1902.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by wattbt** [comment] 2019-04-04 07:22
You have to opt in during the first 2-3 weeks to install 1902 using the script from https://gallery.technet.microsoft.com/ConfigMgr-1902-Enable-87eef616 per announcement:

"Note: As the update is rolled out globally in the coming weeks, it will be automatically downloaded, and you will be notified when it is ready to install from the “Updates and Servicing” node in your Configuration Manager console. If you can’t wait to try these new features, this PowerShell script can be used to ensure that you are in the first wave of customers getting the update. By running this script, you will see the update available in your console right away. "

**Comment by aczechowski** [comment] 2019-04-04 14:44
Thanks @Krytical13 for the feedback, and @wattbt for sharing more info. The [blog post](https://techcommunity.microsoft.com/t5/Configuration-Manager-Blog/Update-1902-for-Configuration-Manager-current-branch-is-now/ba-p/376516 ) for the release includes the note that Ben included. "Fast ring" is the internal term that we use for this initial release for customers that want to opt-in and "go fast". The update will be generally available in a few weeks (what we internally refer to as "slow ring").

I'll keep this issue open for now, but am debating whether or not to mention anything about this in the docs. By design we haven't talked about this in docs for the past three years of current branch updates, and this is the first time as far as I know anyone has asked about it. 😃

**Comment by Krytical13** [comment] 2019-04-04 15:11
If its a non-issue because nobody asks I can understand...

I personally hadn't been following the blog.
After hearing 1902 was released I was just searching "sccm 1902 install" and got 3 different Microsoft pages, none of them that blog.

But when you have a page called "checklist for 1902" relating to installing 1902, you'd think it would include everything required to install now, what is considered "released" now.. or at least there would be reference that you have to wait unless you switch to fast ring.

I spent a little bit of valuable time going through all my config, comparing version numbers and checking logs making sure I didn't miss something in our setup... 

But that's my fault for checking only the official documentation and not the social blog I suppose.

Might be a neat experiment to see how many more fast ring people there are if you added it to doc, as some people might just not know, and might not want to sign up on GitHub to comment on the docs.

Either way thank you for the responses and clarification! Now I know it's official and not a "hack" per say.

**Comment by aczechowski** [comment] 2019-04-04 17:02
Let's keep it open! Thanks for sharing additional thoughts, that's helpful. It's generated some additional discussion with folks on the team... 😄

**Comment by aczechowski** [comment] 2019-04-16 16:58
I'm going to use this issue to track for 1906, to add a note for the checklist as well as the what's new article.

**Comment by aczechowski** [comment] 2019-07-24 03:14
I'm closing this issue because I added information to the checklist for version 1906 to address this feedback. You'll see this new article...soon 😉

**Closed by aczechowski** 2019-07-24 03:14 UTC
Labels: doc-enhancement, triaged
