### ISSUE TITLE
TS Debugger Ignores Disabled Steps/Groups

### ISSUE THREAD

**Issue by yodaut** [MicrosoftDocs/SCCMdocs#1639] opened 2019-06-12 06:52 UTC
Task sequence debugger seems to ignore disabled steps/groups in a task sequence.
To use it properly, you would have to create a modified version of the TS which allows it work with the debugger... Which defeats the purpose of having a debugger.
tl;dr - TS debugger should honor disabled steps/groups or document why it does not.

**Comment by aczechowski** [comment] 2019-06-12 22:01
Thanks @yodaut for taking the time to provide feedback on Configuration Manager! I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.

**Closed by aczechowski** 2019-06-12 22:01 UTC
Labels: product-feedback, triaged

**Comment by aczechowski** [comment] 2019-06-13 14:28
@yodaut FYI I had a quick chat with one of the engineers yesterday, this behavior is currently by design. The task sequence engine skips disabled steps, thus the debugger does as well. (There may be a bug with how disabled *groups* are handled, though.) So if you'd like to see the behavior changed, definitely file feedback.

**Comment by yodaut** [comment] 2019-06-14 00:29
@aczechowski, Thank you for looking into this.
Looking back, I worded this question/feedback poorly.
I meant to say that the Task Sequencer debugger is ignoring the fact that disabled steps are in fact disabled, and trying to run them as part of the Task Sequence anyway. 
In order to use the debugger, I have to delete disabled steps entirely (or set them all to continue on error which is also not ideal).
I see that TP1906 just dropped, so I'll upgrade my lab to that and see if this behavior persists.

**Comment by aczechowski** [comment] 2019-06-14 02:27
I don't think anything changed in 1906tp for this feature. I suggest filing a frown to get your feedback directly to the engineering team.
