### ISSUE TITLE
Version 1802 KB 4163547

### ISSUE THREAD

**Issue by felymich** [MicrosoftDocs/SCCMdocs#761] opened 2018-08-15 17:15 UTC
Hello,
I had an extension of the inventory on the "Local Administrators" class "Win32_LocalAdmins" through a Custom Client Settings Device hardware inventory Set class...
 Apparently it was working fine before the upgrade to 1802 and now it does not take the setting anymore...
I did not see any new settings mentioned in the documentation, did something change?
Thanks,
Dom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54dd8166-9fb1-3027-ad24-6a14c2dd5f3f
* Version Independent ID: 02c01bf8-020c-b29a-ab8f-1541c83743b5
* Content: [Extend hardware inventory - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/inventory/extend-hardware-inventory#BKMK_Enable)
* Content Source: [sccm/core/clients/manage/inventory/extend-hardware-inventory.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/inventory/extend-hardware-inventory.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2018-08-15 20:25
Potential dupe of #583 (or at least related)

**Comment by aczechowski** [comment] 2020-05-12 17:43
Closing as obsolete.

**Closed by aczechowski** 2020-05-12 17:43 UTC
Labels: triaged
