### ISSUE TITLE
Which is Authorititive Documentation?

### ISSUE THREAD

**Issue by MikhailCompo** [MicrosoftDocs/SCCMdocs#1093] opened 2018-12-17 11:19 UTC
https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-variables
https://msdn.microsoft.com/en-gb/library/mt629380.aspx

These two documents are not totally aligned, there are discrepancies, which is authoritative?
e.g. OSDMigrateTimeZone missing from MSDN.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659b0c85-eac7-591e-42d3-8ca629fd6c84
* Version Independent ID: 392139c6-3e46-c0b8-bd1b-ebfc51615fc7
* Content: [Task sequence variable reference - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-variables#OSDMigrateTimeZone)
* Content Source: [sccm/osd/understand/task-sequence-variables.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/understand/task-sequence-variables.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2018-12-17 17:53
@MikhailCompo thanks for the feedback. How did you find the MSDN article? I wasn't aware that was there. 

For all things Configuration Manager current branch: docs.microsoft.com/sccm. If it's anywhere else, it's not official and/or current product documentation.

I'm going to close this issue as there's nothing actionable on this article. But I will followup on that MSDN article. Sorry for the confusion.

**Closed by aczechowski** 2018-12-17 17:53 UTC
Labels: doc-provided, triaged

**Comment by aczechowski** [comment] 2018-12-18 20:09
Thanks @MikhailCompo for reporting this. It turns out to be an issue locale redirection. The en-us article redirects as intended to the docs.microsoft.com article, but any other locale does not. I'm following up to get that fixed.
