### ISSUE TITLE
KB3095113 has been superseded 

### ISSUE THREAD

**Issue by CJRicard** [MicrosoftDocs/SCCMdocs#1287] opened 2019-03-02 04:28 UTC
One such example:  https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=1ee3e8ce-372e-43a0-9b6f-65f25747dfaf.  Catalog has KB3095113 as a hotfix and as an update.

Confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c3e8dd5-a5d0-c96c-841a-21589d58d20b
* Version Independent ID: 09984eaa-b26b-bc94-7250-c4e5db8f5f58
* Content: [Prerequisites for software updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/plan-design/prerequisites-for-software-updates#BKMK_RecoverUpgrades)
* Content Source: [sccm/sum/plan-design/prerequisites-for-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/plan-design/prerequisites-for-software-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2019-03-04 21:18
I'm going to close this issue as a duplicate of #1286. I'll add this note to that issue.

**Closed by aczechowski** 2019-03-04 21:18 UTC
Labels: duplicate, triaged
