### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/SCCMdocs#1547] opened 2019-05-16 19:04 UTC
The url (https://docs.microsoft.com/en-us/sccm/osd/deploy-use/create-phased-deployment-for-task-sequence) has 'create-phased-deployment-for-task-sequence' in it which is not the purpose of this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81e6681-918f-4996-f3e1-b41e8f1e4d22
* Version Independent ID: b45a2ed7-8385-d0a5-1d26-06745d91220c
* Content: [Create phased deployments - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/create-phased-deployment-for-task-sequence#feedback)
* Content Source: [sccm/osd/deploy-use/create-phased-deployment-for-task-sequence.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/create-phased-deployment-for-task-sequence.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by ChrisKibble** [comment] 2019-05-19 06:02
I've confirmed this issue, looks like @Barleyologist is right - perhaps it started as just an article on TS and then grew from there?  I'll work on a fix.

**Comment by aczechowski** [comment] 2019-05-21 19:42
Thanks @Barleyologist for the feedback, and thanks @ChrisKibble for the offer to fix. Correct, it started as an article just for task sequence, and then grew to include other objects. We're using some smoke and mirrors to make the same article show in both the apps and software updates areas of the library, and revised the article to make it encompass all three. So really the only outstanding "issue" is the article file name. Which honestly I'm not all that concerned about. We can technically rename it, but then have a slew of other changes to make (the smoke and mirrors) and make sure the previous URL redirects properly to the new article name. So frankly just more effort than it's worth in my opinion. 😄 

If you're super passionate about it, give me some further explanation and justification so we can consider it further. Otherwise I'm closing this issue.

**Closed by aczechowski** 2019-05-21 19:42 UTC
Labels: docs-experience, triaged
