### ISSUE TITLE
How to use CustomWizardSelectionProfile?

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/SCCMdocs#869] opened 2018-09-28 02:07 UTC
The CustomWizardSelectionProfile of this feature is not clear, can you elaborate how it is used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4452b34-bc38-4e06-a053-c216312dcfc7
* Version Independent ID: ab55107e-272d-1f8f-21dd-dba39a95077d
* Content: [Toolkit reference - Microsoft Deployment Toolkit](https://docs.microsoft.com/en-us/sccm/mdt/toolkit-reference)
* Content Source: [sccm/mdt/toolkit-reference.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdt/toolkit-reference.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2018-10-02 23:51
duplicate of #868, closing this issue.

**Closed by aczechowski** 2018-10-02 23:51 UTC
Labels: duplicate
