### ISSUE TITLE
Comanagement for Laptops on Windows 10 1809

### ISSUE THREAD

**Issue by shaq007** [MicrosoftDocs/SCCMdocs#2195] opened 2020-02-10 21:50 UTC
I have noticed a note "Windows 10 mobile devices don't support co-management" Can you please verify laptops are also included as mobile devices? We have an http enabled SCCM environment and want to implement bitlocker for our laptop devices. So we were considering to use Microsoft Intune for this purpose and enroll the laptops in comanagement to start encrypting our devices using intune features. So will the comanagement not work if the Devices are Windows 10 1809?

**Comment by aczechowski** [comment] 2020-02-11 18:59
Dupe of #2191

**Closed by aczechowski** 2020-02-11 18:59 UTC
Labels: duplicate
