### ISSUE TITLE
SQL 2016 SP2 and SQL 2014 SP3

### ISSUE THREAD

**Issue by matt-k11** [MicrosoftDocs/SCCMdocs#2203] opened 2020-02-14 20:16 UTC
Are SQL Server 2016 SP2 and SQL Server 2014 SP3 versions that are supported by the reporting services point as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c24984-164b-ca1e-a5c4-234eed99b01c
* Version Independent ID: 1073b072-8451-2bf0-bbf1-f5a01e404b60
* Content: [Prerequisites for reporting - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/manage/prerequisites-for-reporting#feedback)
* Content Source: [sccm/core/servers/manage/prerequisites-for-reporting.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/prerequisites-for-reporting.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2020-02-18 18:19
Thanks @matt-k11 for the feedback. I think the short answer is yes, any later service packs are generally supported unless otherwise noted. For example, with our main article on [Supported SQL Server versions](https://docs.microsoft.com/configmgr/core/plan-design/configs/support-for-sql-server-versions#bkmk_SQLVersions) we don't even include the specific SP/CUs anymore.

I'm double-checking with engineering, and the fix here might actually be to remove this section and just point to that main SQL support article.

**Comment by PrajwalDesai** [comment] 2020-02-20 16:38
Yes, I can confirm that SQL Server 2016 SP2 and SQL Server 2014 SP3 versions are supported by the reporting services point. I have an old lab setup still using SQL 2014 SP3. I always install the latest available cumulative update.

**Comment by aczechowski** [comment] 2020-02-20 18:35
@PrajwalDesai, to be clear, just because it works doesn't necessarily mean it's supported. 😉 Our engineering tests regularly tests these combinations to check for performance and functionality. 

I did confirm that we can just collapse this info into the main article on supported versions. So unless we explicitly mark some SP/CU as problematic, assume that any *later* SP/CU versions are supported.

**Comment by aczechowski** [comment] 2020-03-19 00:53
As I previously mentioned, I'm making changes to this article to remove the section on supported versions, and just referring to the main article. The changes will publish live with the 2002 content release, coming soon. I'm closing this issue.

**Closed by aczechowski** 2020-03-19 00:53 UTC
Labels: triaged
