### ISSUE TITLE
No such option: Include autorun.inf file on media

### ISSUE THREAD

**Issue by heldley** [MicrosoftDocs/SCCMdocs#1903] opened 2019-09-29 01:08 UTC
Hi,

We are running 1902, but cannot find this option when creating stand-alone media "Include autorun.inf file on media". According to previous feedback for https://docs.microsoft.com/en-us/sccm/osd/deploy-use/create-bootable-media, this might be also *typo*. The new option might be only valid after 1906
Please kindly review and update

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520657d5-8cfa-a65e-5fe1-02178d1632de
* Version Independent ID: 9acea94e-1728-7de8-88b1-44798f9edcf0
* Content: [Create stand-alone media - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/create-stand-alone-media#feedback)
* Content Source: [sccm/osd/deploy-use/create-stand-alone-media.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/create-stand-alone-media.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2019-09-30 17:18
Dupe of #1900, fixed by private PR MicrosoftDocs/SCCMDocs-pr#4441
Thanks @heldley, I fixed all of these instances with the same pull request. They should all show correctly now as 1906 for the autorun feature.

**Closed by aczechowski** 2019-09-30 17:18 UTC
Labels: duplicate, triaged

**Comment by heldley** [comment] 2019-10-02 10:49
Thanks :)
