### ISSUE TITLE
Bug or Vague/Poor Documentation

### ISSUE THREAD

**Issue by RyanHath** [MicrosoftDocs/SCCMdocs#584] opened 2018-06-06 16:08 UTC
We also use SCEP as our AV, which as you know the definitions are updates. I have my collections that are marked as Server Groups for Clusters, where I deploy regular monthly patches to, not SCEP definitions. I have an ADR that runs for SCEP defs, and deploys to my “All Desktop and Server Clients” collection, which is of course not marked as a server group.

	My collections marked as server groups have simple PS scripts for drain/resume
-	Drain Script &gt; Suspend-ClusterNode -drain
-	Resume Script &gt; Resume-ClusterNode -Failback Immediate

What I’ve noticed is that every day when the ADR runs, and the definitions updates are applied its running the Drain/Resume scripts on the Server Group nodes. When I implemented these server groups my understand is they would only be treated as server groups on deployments deployed directly to the collections marked as server groups.

“When you deploy software updates to a collection that has server group settings configured, Configuration Manager determines how many computers in the collection can install the software updates at any given time and makes the same number of deployment locks available. Only computers that get a deployment lock will start software update installation. When a deployment lock is available, a computer gets the deployment lock, installs the software updates, and then releases the deployment lock when software updates installation successfully completes. Then, the deployment lock becomes available for other computers. If a computer is unable to release a deployment lock, you can manually release all server group deployment locks for the collection.”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f3de375-7539-a500-f8e2-07eb5bf76b08
* Version Independent ID: c660dece-e914-d49a-2a3c-a8de166f88b7
* Content: [Service a server group - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/service-a-server-group#feedback)
* Content Source: [sccm/sum/deploy-use/service-a-server-group.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/service-a-server-group.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2018-06-06 20:26
Thanks @RyanHath for calling this out, and sorry for the difficulty. I confirmed with engineering that this behavior is currently by design: if a resource is in two collections, and one of the collections defines a server group, then it applies to that resource for any deployment to any collection.

**Comment by XabiBeltza** [comment] 2018-08-25 13:56
¿So what's the behaviour if a computer is part of more that one collection with Server Group settings?

**Comment by aczechowski** [comment] 2018-08-28 17:36
Hi @XabiBeltza, thanks for the question. My understanding is that it all depends upon the lock state.

We're working on revamping this feature, in hope to avoid these confusions and questions. Current no ETA, but it is a work in progress.

**Comment by DubstepCat1412** [comment] 2020-03-24 10:10
Is there an update for this problem?

**Comment by aczechowski** [comment] 2020-04-01 22:46
I'm closing this issue. The new **orchestration groups** feature is now available in version 2002. For more information, see https://docs.microsoft.com/configmgr/sum/deploy-use/orchestration-groups

**Closed by aczechowski** 2020-04-01 22:46 UTC
Labels: doc-enhancement, triaged
